// Generated by CoffeeScript 1.6.3
exports.config = {
  debug: true,
  name: 'Giccoo',
  description: 'Giccoo',
  version: '0.1.0',
  site_headers: ['<meta name="author" content="Kelvin" />'],
  host: 'www.Giccoo.com',
  cdn: '',
  site_logo: '',
  site_navs: ['home', 'work', 'services', 'aboutus', 'contact', 'blog', 'company', 'social'],
  site_static_host: '',
  site_enable_search_preview: false,
  site_google_search_domain: 'giccoo.com',
  db: 'mongodb://localhost/giccoo',
  session_secret: 'giccoo_club',
  auth_cookie_name: 'giccoo_club',
  ip: '127.0.0.1',
  port: 8080,
  list_count: 20,
  mail_opts: {
    host: 'smtp.126.com',
    port: 25,
    auth: {
      user: 'club@126.com',
      pass: 'club'
    }
  },
  weibo_key: 10000000,
  plugins: []
};
