// Generated by CoffeeScript 1.6.3
var admin, art, git, sign, user;

art = require('./controllers/art');

user = require('./controllers/user');

git = require('./controllers/git');

admin = require('./controllers/admin');

sign = require('./controllers/sign');

module.exports = function(app) {
  app.get('/', art.homepage);
  app.get('/admin', admin.homepage);
  app.get('/admin/page', admin.pages);
  app.get('/admin/menu', admin.menu);
  app.get('/admin/menu/new', admin.menuNew);
  app.post('/admin/menu/new', admin.menuPost);
  app.get('/sign/in', sign["in"]);
  app.get('/sign/out', sign.out);
  app.post('/sign/in', sign.post);
  app.get('/register', sign.register);
  return app.post('/register', sign.reg);
};

console.log("routes loaded.");
