// Generated by CoffeeScript 1.6.3
var admin, art, git, note, sign, user, work;

art = require('./controllers/art');

work = require('./controllers/work');

user = require('./controllers/user');

git = require('./controllers/git');

admin = require('./controllers/admin');

sign = require('./controllers/sign');

note = require('./controllers/note');

module.exports = function(app) {
  app.get('/', art.homepage);
  app.get('/admin', admin.homepage);
  app.get('/admin/page', admin.pages);
  app.get('/admin/menu', admin.menu);
  app.get('/admin/menu/new', admin.menuNew);
  app.post('/admin/menu/new', admin.menuPost);
  app.get('/admin/work', admin.work);
  app.get('/admin/work/new', admin.workNew);
  app.get('/sign/in', sign["in"]);
  app.get('/sign/out', sign.out);
  app.post('/sign/in', sign.post);
  app.get('/register', sign.register);
  app.post('/register', sign.reg);
  app.get('/work', work.homepage);
  app.get('/work/:shortname', work.art);
  return app.get('*', note.notfind);
};

console.log("routes loaded.");
