// Generated by CoffeeScript 1.6.3
var EventProxy, Menu, User, check, checkAdmin, config, getBk, sanitize;

User = require('../proxy').User;

Menu = require('../proxy').Menu;

check = require('validator').check;

sanitize = require('validator').sanitize;

EventProxy = require('eventproxy');

config = require('../config').config;

checkAdmin = function(req, res) {
  if (req.session.is_admin) {
    return true;
  } else {
    res.render('404');
  }
  return false;
};

exports.homepage = function(req, res, next) {
  if (checkAdmin(req, res)) {
    res.render('admin/homepage');
  }
  return false;
};

exports.pages = function(req, res, next) {
  console.log('pages');
  res.render('admin/page');
  return false;
};

exports.menu = function(req, res, next) {
  Menu.getMenus(function(err, list) {
    console.log(list);
    return res.render('admin/menu', {
      menulist: list
    });
  });
  return false;
};

exports.menuNew = function(req, res, next) {
  console.log('menu New');
  res.render('admin/menu-new');
  return false;
};

exports.menuPost = function(req, res, next) {
  var description, name, url;
  console.log(req.body);
  name = getBk(req.body.menuname);
  url = getBk(req.body.menuurl);
  description = getBk(req.body.editor);
  console.log(name, url, description);
  if (!name) {
    return res.send({
      "rescode": "201",
      "reason": "error name"
    });
  }
  if (!url) {
    return res.send({
      "rescode": "201",
      "reason": "error url"
    });
  }
  if (!description) {
    return res.send({
      "rescode": "201",
      "reason": "error description"
    });
  }
  Menu.newAndSave(name, url, description, 1, function(err) {
    if (err) {
      return next(err);
    }
    res.send({
      "rescode": "200",
      "reason": res.locals.l.error.registersuccess
    });
    return true;
  });
  return false;
};

getBk = function(str) {
  return sanitize(str).trim();
};
