// Generated by CoffeeScript 1.7.1
var EventProxy, User, Ut, Work, check, checkAdmin, config;

User = require('../proxy').User;

Work = require('../proxy').Work;

check = require('validator').check;

EventProxy = require('eventproxy');

config = require('../config').config;

Ut = require('../lib/util');

exports.callback = function(req, res, next) {
  console.log('asdf', req.session.is_admin);
  return next();
};

checkAdmin = function(req, res) {
  if (req.session.is_admin) {
    return true;
  } else {
    return res.render('404');
  }
};

exports.homepage = function(req, res) {
  console.log("work");
  return res.render('work');
};

exports.art = function(req, res, next) {
  return res.render('work');
};

exports.workPost = function(req, res, next) {};
