// Generated by CoffeeScript 1.6.3
var Menu, models;

models = require('../models');

Menu = models.Menu;

exports.getMenus = function(callback) {
  return Menu.find({}, callback);
};

exports.getMenu = function(name, callback) {
  return Menu.findOne({
    name: name
  }, callback);
};

exports.newAndSave = function(name, description, url, order, callback) {
  var menu;
  menu = new Menu();
  menu.name = name;
  menu.url = url;
  menu.order = order;
  menu.description = description;
  return menu.save(callback);
};
