// Generated by CoffeeScript 1.6.3
var Work, models;

models = require('../models');

Work = models.Work;

exports.getWorks = function(language, callback) {
  return Work.find({}, callback);
};

exports.getWorkByNames = function(names, callback) {
  if (names.length === 0) {
    return callback(null, []);
  }
  return Work.find({
    name: {
      $in: names
    }
  }, callback);
};

exports.getWorkById = function(id, callback) {
  return Work.find({
    _id: id
  }, callback);
};

exports.getWorksByQuery = function(query, opt, callback) {
  return Work.find(query, null, opt, callback);
};

exports.newAndSave = function(shortname, title, cotnent, author_id, language, tag_id, callback) {
  var work;
  work = new Work();
  work.shortname = shortname;
  work.title = title;
  work.cotnent = cotnent;
  work.author_id = author_id;
  work.language = language;
  work.tag_id = tag_id;
  return work.save(callback);
};
